<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'title' => 'Hand Painted Bread',
                'slug' => 'hand-painted-bread',
                'image' => '02082022144346-400x400-3.jpg',
                'short_desc' => 'Bread is a staple food prepared from a dough of flour (usually wheat) and water, usually by baking.',
                'description' => '<p>Bread is a staple food prepared from a dough...</p>',
                'extra_desc' => NULL,
                'cost_price' => 15.00,
                'sale_price' => 24.00,
                'old_price' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'is_discount' => 0,
                'is_stock' => 1,
                'sku' => 'T-906',
                'stock_status_id' => 1,
                'stock_qty' => 200,
                'u_stock_qty' => NULL,
                'category_ids' => '4',
                'cat_id' => 4,
                'brand_id' => 3,
                'collection_id' => 0,
                'label_id' => NULL,
                'variation_color' => NULL,
                'variation_size' => 'Kg',
                'tax_id' => 38,
                'is_featured' => 1,
                'is_publish' => 1,
                'user_id' => 1,
                'og_title' => 'Hand Painted Bread',
                'og_description' => 'Bread is a staple food prepared from a dough...',
                'og_keywords' => 'Hand, Painted, Bread',
                'created_at' => Carbon::parse('2025-03-11 00:58:10'),
                'updated_at' => Carbon::parse('2025-03-11 05:38:09')
            ],
            [
                'id' => 2,
                'title' => 'White bread Bakery Sliced bread Loaf',
                'slug' => 'white-bread-bakery-sliced-bread-loaf',
                'image' => '02082022144310-400x400-4.jpg',
                'short_desc' => 'Bread is a staple food prepared from a dough of flour (usually wheat) and water, usually by baking.',
                'description' => '<p>Bread is a staple food prepared from a dough...</p>',
                'extra_desc' => NULL,
                'cost_price' => 40.00,
                'sale_price' => 50.00,
                'old_price' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'is_discount' => 0,
                'is_stock' => 1,
                'sku' => 'WB-3489',
                'stock_status_id' => 1,
                'stock_qty' => 400,
                'u_stock_qty' => NULL,
                'category_ids' => '4',
                'cat_id' => 4,
                'brand_id' => 5,
                'collection_id' => 0,
                'label_id' => NULL,
                'variation_color' => NULL,
                'variation_size' => 'Kg',
                'tax_id' => 38,
                'is_featured' => 1,
                'is_publish' => 1,
                'user_id' => 1,
                'og_title' => 'White bread Bakery Sliced bread Loaf',
                'og_description' => 'Bread is a staple food prepared from a dough...',
                'og_keywords' => 'White bread, Bakery, Sliced bread, Loaf',
                'created_at' => Carbon::parse('2025-03-11 06:01:13'),
                'updated_at' => Carbon::parse('2025-03-11 11:34:44')
            ],
            [
                'id' => 3,
                'title' => 'Croissant Pain au chocolat Viennoiserie Danish pastry Puff pastry',
                'slug' => 'croissant-pain-au-chocolat-viennoiserie-danish-pastry-puff-pastry-2',
                'f_thumbnail' => '19082022103844-400x400-2-pastry.jpg',
                'short_desc' => 'Pastry is baked food made with a dough of flour, water and shortening (solid fats, including butter or lard) that may be savoury or sweetened.',
                'description' => '<p>The pastry is baked food made with a dough...</p>',
                'extra_desc' => NULL,
                'cost_price' => 30.00,
                'sale_price' => 40.00,
                'old_price' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'is_discount' => 1,
                'is_stock' => 1,
                'sku' => 'P-43546',
                'stock_status_id' => 1,
                'stock_qty' => 200,
                'u_stock_qty' => NULL,
                'category_ids' => '4',
                'cat_id' => 4,
                'brand_id' => 3,
                'collection_id' => 0,
                'label_id' => NULL,
                'variation_color' => NULL,
                'variation_size' => 'Kg',
                'tax_id' => 38,
                'is_featured' => 1,
                'is_publish' => 1,
                'user_id' => 1,
                'og_title' => 'Croissant Pain au chocolat Viennoiserie Danish pastry Puff pastry',
                'og_description' => 'Pastry is baked food made with a dough...',
                'og_keywords' => 'Croissant Pain au chocolat Viennoiserie Danish pastry Puff pastry',
                'created_at' => Carbon::parse('2022-07-31 06:20:31'),
                'updated_at' => Carbon::parse('2022-08-22 11:33:31'),
            ],
            [
                'id' => 4,
                'title' => 'Green tea Coffee Iced tea Lemon',
                'slug' => 'green-tea-coffee-iced-tea-lemon',
                'image' => '19082022103010-400x400-1-green-tea.jpg',
                'short_desc' => 'Green tea is a type of tea that is made from Camellia sinensis leaves',
                'description' => '<p>Green tea is a type of tea...</p>',
                'extra_desc' => NULL,
                'cost_price' => 90.00,
                'sale_price' => 100.00,
                'old_price' => 125.00,
                'start_date' => '2022-09-02',
                'end_date' => '2022-08-06',
                'is_discount' => 0,
                'is_stock' => 1,
                'sku' => 'GT-7842',
                'stock_status_id' => 1,
                'stock_qty' => 400,
                'u_stock_qty' => NULL,
                'category_ids' => '11',
                'cat_id' => 11,
                'brand_id' => 5,
                'collection_id' => 0,
                'label_id' => NULL,
                'variation_color' => NULL,
                'variation_size' => 'Box',
                'tax_id' => 38,
                'is_featured' => 1,
                'is_publish' => 1,
                'user_id' => 1,
                'og_title' => 'Green tea Coffee Iced tea Lemon',
                'og_description' => 'Green tea is a type of tea...',
                'og_keywords' => 'Green tea Coffee Iced tea Lemon',
                'created_at' => Carbon::parse('2022-07-31 07:31:08'),
                'updated_at' => Carbon::parse('2022-09-02 05:34:14'),
            ],
            [
                'id' => 5,
                'title' => 'Walnuts',
                'slug' => 'walnuts',
                'image' => '01082022172737-400x400-3.jpg',
                'short_desc' => 'Dried food products are often laden with bacterial and fungal spores.',
                'description' => '<p>Dried food products are often laden with bacterial and fungal spores.</p>',
                'cost_price' => 90.000,
                'sale_price' => 110.000,
                'old_price' => 170.000,
                'start_date' => '2022-09-02',
                'end_date' => '2023-09-03',
                'is_discount' => 1,
                'is_stock' => 1,
                'sku' => 'DF-564',
                'stock_status_id' => 1,
                'stock_qty' => 900,
                'category_ids' => '3',
                'cat_id' => 3,
                'brand_id' => 5,
                'collection_id' => 1,
                'tax_id' => 38,
                'is_featured' => 1,
                'is_publish' => 1,
                'user_id' => 2,
                'og_title' => 'Walnuts',
                'og_description' => 'Dried food products are often laden with bacterial and fungal spores.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'Pistachio',
                'slug' => 'pistachio-2',
                'image' => '01082022172712-400x400-7.jpg',
                'short_desc' => 'Dried food products are often laden with bacterial and fungal spores.',
                'description' => '<p>Dried food products are often laden with bacterial and fungal spores.</p>',
                'cost_price' => 50.000,
                'sale_price' => 60.000,
                'start_date' => null,
                'end_date' => null,
                'is_discount' => 0,
                'is_stock' => 1,
                'sku' => 'TP-765',
                'stock_status_id' => 1,
                'stock_qty' => 500,
                'category_ids' => '3',
                'cat_id' => 3,
                'brand_id' => 2,
                'collection_id' => 0,
                'tax_id' => 38,
                'is_featured' => 1,
                'is_publish' => 1,
                'user_id' => 1,
                'og_title' => 'Pistachio',
                'og_description' => 'Dried food products are often laden with bacterial and fungal spores.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
